package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"

	"github.com/thanhhaudev/go-graphql/src/graph/generated"
	"github.com/thanhhaudev/go-graphql/src/graph/model"
)

// Books is the resolver for the books field.
// this is the sub-resolver for the books field in the Author type. So, it will be called for each author in the list of authors.
// Use the data loader to load the books for the author instead of querying the database directly to optimize the performance.
func (r *authorResolver) Books(ctx context.Context, obj *model.Author) ([]*model.Book, error) {
	books, err := r.bookService.GetByAuthorID(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	return books, nil
}

// Author returns generated.AuthorResolver implementation.
func (r *Resolver) Author() generated.AuthorResolver { return &authorResolver{r} }

type authorResolver struct{ *Resolver }
