package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"
	"time"

	"github.com/thanhhaudev/go-graphql/src/graph/generated"
	"github.com/thanhhaudev/go-graphql/src/graph/model"
)

// BirthDate is the resolver for the birthDate field.
func (r *borrowerResolver) BirthDate(ctx context.Context, obj *model.Borrower) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: BirthDate - birthDate"))
}

// Books is the resolver for the books field.
func (r *borrowerResolver) Books(ctx context.Context, obj *model.Borrower) ([]*model.Book, error) {
	books, err := r.bookService.FindBooksByBorrowerID(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	return books, nil
}

// Borrower returns generated.BorrowerResolver implementation.
func (r *Resolver) Borrower() generated.BorrowerResolver { return &borrowerResolver{r} }

type borrowerResolver struct{ *Resolver }
