package seeder

import (
	"log"
	"time"

	"github.com/thanhhaudev/go-graphql/src/graph/model"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

var (
	Authors = []*model.Author{
		{
			Name:      "J.K. Rowling",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "George R.R. Martin",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "J.R.R. Tolkien",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Stephen King",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Agatha Christie",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Mark Twain",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Ernest Hemingway",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "F. Scott Fitzgerald",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Charles Dickens",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Jane Austen",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Leo Tolstoy",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Gabriel Garcia Marquez",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Haruki Murakami",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Toni Morrison",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Isabel Allende",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "George Orwell",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Nguyễn Nhật Ánh",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Nguyễn Du",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Xuân Diệu",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Hồ Chí Minh",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Nam Cao",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
	}
	Books = []*model.Book{
		{
			Title:       "Harry Potter and the Sorcerer's Stone",
			Description: "A young wizard embarks on his journey to defeat the dark wizard Voldemort.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[0]}, // J.K. Rowling
			PublishAt:   time.Date(1997, 6, 26, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Harry Potter and the Chamber of Secrets",
			Description: "Harry's second year at Hogwarts is marked by the opening of the Chamber of Secrets.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[0]}, // J.K. Rowling
			PublishAt:   time.Date(1998, 7, 2, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Harry Potter and the Prisoner of Azkaban",
			Description: "Harry's third year at Hogwarts is marked by the escape of Sirius Black.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[0]},
			PublishAt:   time.Date(1999, 7, 8, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Harry Potter and the Goblet of Fire",
			Description: "Harry's fourth year at Hogwarts is marked by the Triwizard Tournament.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[0]},
			PublishAt:   time.Date(2000, 7, 8, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Harry Potter and the Order of the Phoenix",
			Description: "Harry's fifth year at Hogwarts is filled with new challenges and the rise of the Order of the Phoenix.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[0]},
			PublishAt:   time.Date(2003, 6, 21, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Harry Potter and the Half-Blood Prince",
			Description: "Harry's sixth year at Hogwarts reveals the identity of the Half-Blood Prince.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[0]},
			PublishAt:   time.Date(2005, 7, 16, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Harry Potter and the Deathly Hallows",
			Description: "Harry's final year at Hogwarts is marked by the quest to destroy Voldemort's Horcruxes.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[0]},
			PublishAt:   time.Date(2007, 7, 21, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "A Clash of Kings",
			Description: "The second book in the A Song of Ice and Fire series, continuing the saga of the Seven Kingdoms.",
			Quantity:    75,
			Rating:      5,
			Authors:     []*model.Author{Authors[1]}, // George R.R. Martin
			PublishAt:   time.Date(1998, 11, 16, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "A Game of Thrones",
			Description: "A political struggle in the Seven Kingdoms of Westeros, involving great families and dragons.",
			Quantity:    75,
			Rating:      5,
			Authors:     []*model.Author{Authors[1]}, // George R.R. Martin
			PublishAt:   time.Date(1996, 8, 6, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "A Storm of Swords",
			Description: "The third book in the A Song of Ice and Fire series, featuring the War of the Five Kings.",
			Quantity:    75,
			Rating:      5,
			Authors:     []*model.Author{Authors[1]},
			PublishAt:   time.Date(2000, 8, 8, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "A Feast for Crows",
			Description: "The fourth book in the A Song of Ice and Fire series, focusing on the aftermath of the War of the Five Kings.",
			Quantity:    75,
			Rating:      5,
			Authors:     []*model.Author{Authors[1]},
			PublishAt:   time.Date(2005, 10, 17, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "A Dance with Dragons",
			Description: "The fifth book in the A Song of Ice and Fire series, continuing the storylines of the previous books.",
			Quantity:    75,
			Rating:      5,
			Authors:     []*model.Author{Authors[1]},
			PublishAt:   time.Date(2011, 7, 12, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "The Hobbit",
			Description: "A hobbit named Bilbo Baggins embarks on a quest to reclaim a treasure guarded by a dragon.",
			Quantity:    50,
			Rating:      5,
			Authors:     []*model.Author{Authors[2]}, // J.R.R. Tolkien
			PublishAt:   time.Date(1937, 9, 21, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "The Shining",
			Description: "A family becomes trapped in a haunted hotel during the winter.",
			Quantity:    60,
			Rating:      5,
			Authors:     []*model.Author{Authors[3]}, // Stephen King
			PublishAt:   time.Date(1977, 1, 28, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "It",
			Description: "A horror novel about a group of children who are terrorized by a malevolent entity.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[3]},
			PublishAt:   time.Date(1986, 9, 15, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "The Dark Tower: The Gunslinger",
			Description: "The first book in The Dark Tower series, following the journey of Roland Deschain.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[3]},
			PublishAt:   time.Date(1982, 6, 10, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Misery",
			Description: "A psychological horror novel about an author held captive by an obsessed fan.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[3]},
			PublishAt:   time.Date(1987, 6, 8, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "The Stand",
			Description: "A post-apocalyptic horror novel about a pandemic that wipes out most of the human population.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[3]},
			PublishAt:   time.Date(1978, 10, 3, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Carrie",
			Description: "A horror novel about a high school girl with telekinetic powers.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[3]},
			PublishAt:   time.Date(1974, 4, 5, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Murder on the Orient Express",
			Description: "A detective investigates a murder on a famous train.",
			Quantity:    80,
			Rating:      5,
			Authors:     []*model.Author{Authors[4]}, // Agatha Christie
			PublishAt:   time.Date(1934, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Adventures of Huckleberry Finn",
			Description: "A boy and a runaway slave journey down the Mississippi River.",
			Quantity:    40,
			Rating:      4,
			Authors:     []*model.Author{Authors[5]}, // Mark Twain
			PublishAt:   time.Date(1884, 12, 10, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "The Adventures of Tom Sawyer",
			Description: "A novel about a young boy growing up along the Mississippi River.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[5]},
			PublishAt:   time.Date(1876, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "The Prince and the Pauper",
			Description: "A novel about two boys who exchange their lives.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[5]},
			PublishAt:   time.Date(1881, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "A Connecticut Yankee in King Arthur's Court",
			Description: "A novel about a man who travels back in time to the court of King Arthur.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[5]},
			PublishAt:   time.Date(1889, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "The Tragedy of Pudd'nhead Wilson",
			Description: "A novel about a lawyer who solves a crime using fingerprint evidence.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[5]},
			PublishAt:   time.Date(1894, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "The Innocents Abroad",
			Description: "A travel book about Twain's journey through Europe and the Holy Land.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[5]},
			PublishAt:   time.Date(1869, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "The Old Man and the Sea",
			Description: "An aging fisherman struggles to catch a giant marlin.",
			Quantity:    45,
			Rating:      5,
			Authors:     []*model.Author{Authors[6]}, // Ernest Hemingway
			PublishAt:   time.Date(1952, 9, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "The Great Gatsby",
			Description: "A mysterious millionaire throws lavish parties in search of a lost love.",
			Quantity:    90,
			Rating:      5,
			Authors:     []*model.Author{Authors[7]}, // F. Scott Fitzgerald
			PublishAt:   time.Date(1925, 4, 10, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Tender Is the Night",
			Description: "A novel about the rise and fall of Dick Diver, a charming and talented psychiatrist.",
			Quantity:    23,
			Rating:      5,
			Authors:     []*model.Author{Authors[7]},
			PublishAt:   time.Date(1934, 4, 12, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "This Side of Paradise",
			Description: "A novel that examines the lives and morality of post-World War I youth.",
			Quantity:    78,
			Rating:      5,
			Authors:     []*model.Author{Authors[7]},
			PublishAt:   time.Date(1920, 3, 26, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "The Beautiful and Damned",
			Description: "A novel about the troubled marriage of Anthony and Gloria Patch.",
			Quantity:    43,
			Rating:      5,
			Authors:     []*model.Author{Authors[7]},
			PublishAt:   time.Date(1922, 3, 4, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "The Last Tycoon",
			Description: "An unfinished novel about the rise to power of Hollywood mogul Monroe Stahr.",
			Quantity:    65,
			Rating:      5,
			Authors:     []*model.Author{Authors[7]},
			PublishAt:   time.Date(1941, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Flappers and Philosophers",
			Description: "A collection of short stories that established Fitzgerald as a master of the short story form.",
			Quantity:    45,
			Rating:      5,
			Authors:     []*model.Author{Authors[7]},
			PublishAt:   time.Date(1920, 9, 10, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "A Tale of Two Cities",
			Description: "A story set during the French Revolution, focusing on themes of sacrifice and resurrection.",
			Quantity:    85,
			Rating:      5,
			Authors:     []*model.Author{Authors[8]}, // Charles Dickens
			PublishAt:   time.Date(1859, 4, 30, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Pride and Prejudice",
			Description: "A romantic novel about manners, upbringing, and marriage in early 19th-century England.",
			Quantity:    70,
			Rating:      5,
			Authors:     []*model.Author{Authors[9]}, // Jane Austen
			PublishAt:   time.Date(1813, 1, 28, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "War and Peace",
			Description: "A historical novel set during the Napoleonic Wars, focusing on five aristocratic families.",
			Quantity:    30,
			Rating:      5,
			Authors:     []*model.Author{Authors[10]}, // Leo Tolstoy
			PublishAt:   time.Date(1869, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Anna Karenina",
			Description: "A tragic story of love and infidelity set in 19th-century Russia.",
			Quantity:    98,
			Rating:      5,
			Authors:     []*model.Author{Authors[10]},
			PublishAt:   time.Date(1877, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "The Death of Ivan Ilyich",
			Description: "A novella about the existential reflections of a dying man.",
			Quantity:    53,
			Rating:      5,
			Authors:     []*model.Author{Authors[10]},
			PublishAt:   time.Date(1886, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Resurrection",
			Description: "A novel about a nobleman's quest for redemption.",
			Quantity:    34,
			Rating:      5,
			Authors:     []*model.Author{Authors[10]},
			PublishAt:   time.Date(1899, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Hadji Murat",
			Description: "A novella about a Chechen rebel who fights against the Russian Empire.",
			Quantity:    53,
			Rating:      5,
			Authors:     []*model.Author{Authors[10]},
			PublishAt:   time.Date(1912, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Childhood",
			Description: "The first part of Tolstoy's autobiographical trilogy.",
			Quantity:    22,
			Rating:      5,
			Authors:     []*model.Author{Authors[10]},
			PublishAt:   time.Date(1852, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "One Hundred Years of Solitude",
			Description: "A multi-generational story about the Buendía family in a fictional town in Colombia.",
			Quantity:    55,
			Rating:      5,
			Authors:     []*model.Author{Authors[11]}, // Gabriel Garcia Marquez
			PublishAt:   time.Date(1967, 5, 30, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Norwegian Wood",
			Description: "A nostalgic story of loss, sexuality, and emotional turmoil in 1960s Japan.",
			Quantity:    65,
			Rating:      5,
			Authors:     []*model.Author{Authors[12]}, // Haruki Murakami
			PublishAt:   time.Date(1987, 9, 4, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Kafka on the Shore",
			Description: "A metaphysical novel blending reality and fantasy.",
			Quantity:    50,
			Rating:      5,
			Authors:     []*model.Author{Authors[12]},
			PublishAt:   time.Date(2002, 9, 12, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "1Q84",
			Description: "A dystopian novel set in a parallel world.",
			Quantity:    60,
			Rating:      5,
			Authors:     []*model.Author{Authors[12]},
			PublishAt:   time.Date(2009, 5, 29, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "The Wind-Up Bird Chronicle",
			Description: "A novel about a man's search for his missing wife.",
			Quantity:    70,
			Rating:      5,
			Authors:     []*model.Author{Authors[12]},
			PublishAt:   time.Date(1994, 4, 12, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Norwegian Wood",
			Description: "A nostalgic story of loss, sexuality, and emotional turmoil in 1960s Japan.",
			Quantity:    65,
			Rating:      5,
			Authors:     []*model.Author{Authors[12]},
			PublishAt:   time.Date(1987, 9, 4, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "After Dark",
			Description: "A novel that takes place over the course of one night in Tokyo.",
			Quantity:    55,
			Rating:      5,
			Authors:     []*model.Author{Authors[12]},
			PublishAt:   time.Date(2004, 9, 29, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Beloved",
			Description: "A novel about the aftereffects of slavery and the haunting of one family.",
			Quantity:    35,
			Rating:      5,
			Authors:     []*model.Author{Authors[13]}, // Toni Morrison
			PublishAt:   time.Date(1987, 9, 16, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "The House of the Spirits",
			Description: "A family saga set in Chile, blending magical realism with political events.",
			Quantity:    40,
			Rating:      5,
			Authors:     []*model.Author{Authors[14]}, // Isabel Allende
			PublishAt:   time.Date(1982, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "1984",
			Description: "A dystopian novel about a totalitarian regime that uses surveillance and thought control.",
			Quantity:    95,
			Rating:      5,
			Authors:     []*model.Author{Authors[15]}, // George Orwell
			PublishAt:   time.Date(1949, 6, 8, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Animal Farm",
			Description: "A satirical allegory of Soviet totalitarianism.",
			Quantity:    80,
			Rating:      5,
			Authors:     []*model.Author{Authors[15]},
			PublishAt:   time.Date(1945, 8, 17, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Homage to Catalonia",
			Description: "A personal account of Orwell's experiences in the Spanish Civil War.",
			Quantity:    60,
			Rating:      5,
			Authors:     []*model.Author{Authors[15]},
			PublishAt:   time.Date(1938, 4, 25, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Down and Out in Paris and London",
			Description: "A memoir of Orwell's time living in poverty.",
			Quantity:    50,
			Rating:      5,
			Authors:     []*model.Author{Authors[15]},
			PublishAt:   time.Date(1933, 1, 9, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "The Road to Wigan Pier",
			Description: "An investigation into the living conditions of the working class in England.",
			Quantity:    55,
			Rating:      5,
			Authors:     []*model.Author{Authors[15]},
			PublishAt:   time.Date(1937, 3, 8, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Keep the Aspidistra Flying",
			Description: "A novel about a man who rebels against the commercialism of society.",
			Quantity:    45,
			Rating:      5,
			Authors:     []*model.Author{Authors[15]},
			PublishAt:   time.Date(1936, 4, 20, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Kính Vạn Hoa",
			Description: "A series of stories about the adventures of three friends.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[16]},
			PublishAt:   time.Date(1995, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Cho Tôi Xin Một Vé Đi Tuổi Thơ",
			Description: "A nostalgic story about childhood memories.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[16]},
			PublishAt:   time.Date(2008, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Ngồi Khóc Trên Cây",
			Description: "A touching story about love and loss.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[16]},
			PublishAt:   time.Date(2013, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Cô Gái Đến Từ Hôm Qua",
			Description: "A romantic story about a boy and his first love.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[16]},
			PublishAt:   time.Date(1990, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Mắt Biếc",
			Description: "A story about unrequited love and the passage of time.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[16]},
			PublishAt:   time.Date(1990, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Truyện Kiều",
			Description: "An epic poem about the life and trials of Thúy Kiều.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[17]},
			PublishAt:   time.Date(1820, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Văn Tế Thập Loại Chúng Sinh",
			Description: "A poem lamenting the fate of the ten types of beings.",
			Quantity:    80,
			Rating:      5,
			Authors:     []*model.Author{Authors[17]},
			PublishAt:   time.Date(1802, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Độc Tiểu Thanh Ký",
			Description: "A poem reflecting on the life of a Chinese woman named Tiểu Thanh.",
			Quantity:    70,
			Rating:      5,
			Authors:     []*model.Author{Authors[17]},
			PublishAt:   time.Date(1810, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Thác Lời Trai Phường Nón",
			Description: "A satirical poem about the life of a hat seller.",
			Quantity:    60,
			Rating:      5,
			Authors:     []*model.Author{Authors[17]},
			PublishAt:   time.Date(1815, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Văn Tế Sĩ Phu Cần Giuộc",
			Description: "A poem honoring the fallen soldiers of Cần Giuộc.",
			Quantity:    50,
			Rating:      5,
			Authors:     []*model.Author{Authors[17]},
			PublishAt:   time.Date(1861, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Thơ Thơ",
			Description: "A collection of Xuân Diệu's early poems.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[18]},
			PublishAt:   time.Date(1938, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Gửi Hương Cho Gió",
			Description: "A collection of romantic poems.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[18]},
			PublishAt:   time.Date(1945, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Mơ Mộng",
			Description: "A collection of poems about dreams and aspirations.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[18]},
			PublishAt:   time.Date(1940, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Lửa Thiêng",
			Description: "A collection of patriotic poems.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[18]},
			PublishAt:   time.Date(1942, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Nhật Ký Trong Tù",
			Description: "A collection of poems written by Hồ Chí Minh during his imprisonment.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[19]},
			PublishAt:   time.Date(1943, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Đường Kách Mệnh",
			Description: "A book outlining the revolutionary path for Vietnam.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[19]},
			PublishAt:   time.Date(1927, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Bản Án Chế Độ Thực Dân Pháp",
			Description: "A critique of French colonialism in Vietnam.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[19]},
			PublishAt:   time.Date(1925, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Tuyên Ngôn Độc Lập",
			Description: "The Declaration of Independence of Vietnam.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[19]},
			PublishAt:   time.Date(1945, 9, 2, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Chí Phèo",
			Description: "A story about the life of a poor farmer who becomes a notorious criminal.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[20]},
			PublishAt:   time.Date(1941, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Lão Hạc",
			Description: "A touching story about an old man and his dog.",
			Quantity:    500,
			Rating:      5,
			Authors:     []*model.Author{Authors[20]},
			PublishAt:   time.Date(1943, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Sống Mòn",
			Description: "A novel about the struggles of a poor teacher.",
			Quantity:    180,
			Rating:      5,
			Authors:     []*model.Author{Authors[20]},
			PublishAt:   time.Date(1944, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Đời Thừa",
			Description: "A story about the life of a writer who feels his life is wasted.",
			Quantity:    100,
			Rating:      5,
			Authors:     []*model.Author{Authors[20]},
			PublishAt:   time.Date(1943, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
		{
			Title:       "Trăng Sáng",
			Description: "A collection of short stories reflecting the social issues of the time.",
			Quantity:    120,
			Rating:      5,
			Authors:     []*model.Author{Authors[20]},
			PublishAt:   time.Date(1942, 1, 1, 0, 0, 0, 0, time.UTC),
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		},
	}
	Borrowers = []*model.Borrower{
		{
			Name:      "John Smith",
			Address:   "123 Elm Street",
			TelNumber: "555-1234",
			BirthDate: datatypes.Date(time.Date(1980, 1, 1, 0, 0, 0, 0, time.UTC)),
			Books:     []*model.Book{Books[0], Books[1]}, // Harry Potter and A Game of Thrones
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Alice Johnson",
			Address:   "456 Oak Avenue",
			TelNumber: "555-5678",
			BirthDate: datatypes.Date(time.Date(1990, 2, 2, 0, 0, 0, 0, time.UTC)),
			Books:     []*model.Book{Books[2]}, // The Hobbit
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Michael Brown",
			Address:   "789 Pine Road",
			TelNumber: "555-8765",
			BirthDate: datatypes.Date(time.Date(1975, 3, 3, 0, 0, 0, 0, time.UTC)),
			Books:     []*model.Book{Books[3], Books[4]}, // The Shining and Murder on the Orient Express
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Emily Davis",
			Address:   "101 Maple Lane",
			TelNumber: "555-4321",
			BirthDate: datatypes.Date(time.Date(1985, 4, 4, 0, 0, 0, 0, time.UTC)),
			Books:     []*model.Book{Books[5], Books[6]}, // Adventures of Huckleberry Finn and The Old Man and the Sea
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "James Wilson",
			Address:   "202 Birch Boulevard",
			TelNumber: "555-6789",
			BirthDate: datatypes.Date(time.Date(1995, 5, 5, 0, 0, 0, 0, time.UTC)),
			Books:     []*model.Book{Books[7]}, // The Great Gatsby
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Sophia Martinez",
			Address:   "303 Cedar Street",
			TelNumber: "555-9876",
			BirthDate: datatypes.Date(time.Date(1988, 6, 6, 0, 0, 0, 0, time.UTC)),
			Books:     []*model.Book{Books[8]}, // A Tale of Two Cities
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Daniel Anderson",
			Address:   "404 Walnut Avenue",
			TelNumber: "555-5432",
			BirthDate: datatypes.Date(time.Date(1978, 7, 7, 0, 0, 0, 0, time.UTC)),
			Books:     []*model.Book{Books[9], Books[10]}, // Pride and Prejudice and War and Peace
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Jessica Lee",
			Address:   "505 Chestnut Road",
			TelNumber: "555-6543",
			BirthDate: datatypes.Date(time.Date(1982, 8, 8, 0, 0, 0, 0, time.UTC)),
			Books:     []*model.Book{Books[11]}, // One Hundred Years of Solitude
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Christopher Garcia",
			Address:   "606 Spruce Lane",
			TelNumber: "555-3210",
			BirthDate: datatypes.Date(time.Date(1992, 9, 9, 0, 0, 0, 0, time.UTC)),
			Books:     []*model.Book{Books[12]}, // Norwegian Wood
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Olivia Martinez",
			Address:   "707 Redwood Boulevard",
			TelNumber: "555-2109",
			BirthDate: datatypes.Date(time.Date(1984, 10, 10, 0, 0, 0, 0, time.UTC)),
			Books:     []*model.Book{Books[13]}, // Beloved
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "David Taylor",
			Address:   "808 Cypress Street",
			TelNumber: "555-1098",
			BirthDate: datatypes.Date(time.Date(1976, 11, 11, 0, 0, 0, 0, time.UTC)),
			Books:     []*model.Book{Books[14]}, // The House of the Spirits
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Chloe White",
			Address:   "909 Fir Avenue",
			TelNumber: "555-0987",
			BirthDate: datatypes.Date(time.Date(1991, 12, 12, 0, 0, 0, 0, time.UTC)),
			Books:     []*model.Book{Books[15]}, // 1984
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Nguyễn Văn Nam",
			Address:   "123 Đường Lê Lợi, Quận 1, TP. Hồ Chí Minh",
			TelNumber: "0901234567",
			BirthDate: datatypes.Date(time.Date(1990, 1, 1, 0, 0, 0, 0, time.UTC)),
			Books:     []*model.Book{Books[0], Books[1]},
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Trần Thị Mai",
			Address:   "456 Đường Nguyễn Huệ, Quận 1, TP. Hồ Chí Minh",
			TelNumber: "0902345678",
			BirthDate: datatypes.Date(time.Date(1985, 2, 2, 0, 0, 0, 0, time.UTC)),
			Books:     []*model.Book{Books[2]},
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Lê Văn Hùng",
			Address:   "789 Đường Trần Hưng Đạo, Quận 5, TP. Hồ Chí Minh",
			TelNumber: "0903456789",
			BirthDate: datatypes.Date(time.Date(1980, 3, 3, 0, 0, 0, 0, time.UTC)),
			Books:     []*model.Book{Books[3], Books[4]},
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Phạm Thị Hồng",
			Address:   "123 Đường Trần Phú, Quận 5, TP. Hồ Chí Minh",
			TelNumber: "0904567890",
			BirthDate: datatypes.Date(time.Date(1993, 4, 4, 0, 0, 0, 0, time.UTC)),
			Books:     []*model.Book{Books[5], Books[6]},
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Đỗ Văn Minh",
			Address:   "456 Đường Lý Thường Kiệt, Quận 10, TP. Hồ Chí Minh",
			TelNumber: "0905678901",
			BirthDate: datatypes.Date(time.Date(1987, 5, 5, 0, 0, 0, 0, time.UTC)),
			Books:     []*model.Book{Books[7]},
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Nguyễn Thị Lan",
			Address:   "789 Đường Nguyễn Trãi, Quận 1, TP. Hồ Chí Minh",
			TelNumber: "0906789012",
			BirthDate: datatypes.Date(time.Date(1995, 6, 6, 0, 0, 0, 0, time.UTC)),
			Books:     []*model.Book{Books[8]},
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Lê Văn Tùng",
			Address:   "101 Đường Phạm Ngũ Lão, Quận 3, TP. Hồ Chí Minh",
			TelNumber: "0907890123",
			BirthDate: datatypes.Date(time.Date(1982, 7, 7, 0, 0, 0, 0, time.UTC)),
			Books:     []*model.Book{Books[9], Books[10]},
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			Name:      "Trần Thị Hạnh",
			Address:   "202 Đường Nguyễn Văn Cừ, Quận 4, TP. Hồ Chí Minh",
			TelNumber: "0908901234",
			BirthDate: datatypes.Date(time.Date(1990, 8, 8, 0, 0, 0, 0, time.UTC)),
			Books:     []*model.Book{Books[11]},
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
	}
)

func SeedAuthors(db *gorm.DB, authors []*model.Author) {
	var count int64
	db.Model(&model.Author{}).Count(&count)

	if count == 0 {

		if err := db.Create(&authors).Error; err != nil {
			log.Fatalf("could not seed users: %v", err)
		}
		log.Println("Users table seeded.")
	} else {
		log.Println("Users table already contains data.")
	}
}

func SeedBooks(db *gorm.DB, books []*model.Book) {
	var count int64
	db.Model(&model.Book{}).Count(&count)
	if count == 0 {
		if err := db.CreateInBatches(&books, 30).Error; err != nil {
			log.Fatalf("could not seed books: %v", err)
		}
		log.Println("Books table seeded.")
	} else {
		log.Println("Books table already contains data.")
	}
}

func SeedBorrowers(db *gorm.DB, borrowers []*model.Borrower) {
	var count int64
	db.Model(&model.Borrower{}).Count(&count)
	if count == 0 {
		if err := db.Create(&borrowers).Error; err != nil {
			log.Fatalf("could not seed borrowers: %v", err)
		}
		log.Println("Borrowers table seeded.")
	} else {
		log.Println("Borrowers table already contains data.")
	}
}
